### PR TITLE
Create ReduxSimple.yml

### PR DESCRIPTION
**Pull request by Odonno**

### CODE REVIEW

**Comment by japierdolewszystkozajete27** [comment]
Docs that are readme are not required to be specified.
For NuGet packages, project name is enough

```
Source: https://github.com/Odonno/ReduxSimple
NuGet: ReduxSimple
Language: C#
Image: https://raw.githubusercontent.com/Odonno/ReduxSimple/master/images/logo.png
Tags:
  - Redux
  - Reactive
  - State management
```

**Comment by Odonno** [comment]
@japierdolewszystkozajete27 Thanks. I made the change.

**Comment by daveaglick** [comment]
Thanks!

**Comment by Odonno** [comment]
Thank you.

**Pull request merged**
