### PR TITLE
Add awesome-dotnet-core-resources.yml

### PR DESCRIPTION
**Pull request by meysamhadeli**

### CODE REVIEW

**Comment by daveaglick** [comment]
It looks like the resource link is going to a blog. Is there a better link for this resource (I'm assuming this is supposed to link to an awesome-style list of things)? If not, this would be better in the blog section.

**Comment by meysamhadeli** [comment]
> It looks like the resource link is going to a blog. Is there a better link for this resource (I'm assuming this is supposed to link to an awesome-style list of things)? If not, this would be better in the blog section.

No it's not a blog link. It's an awesome-style list.
It's like https://github.com/daveaglick/discoverdotnet/blob/master/data/resources/awesome-microservices-netcore.yml.

**Comment by daveaglick** [comment]
Can you double-check the link in the PR file? This is what I see when I go there:

image

**Comment by meysamhadeli** [comment]
> Can you double-check the link in the PR file? This is what I see when I go there:
> 
> image

Sorry, I fix link website.

**Comment by daveaglick** [comment]
Thanks for the correction! Running a build check now and then will merge.

**Pull request merged**
