### PR TITLE
Create quickenshtein.yml

### PR DESCRIPTION
**Pull request by Turnerj**

### CODE REVIEW

**Comment by Turnerj** [comment]
Had a quick look at the error the CI was throwing though doesn't seem to be anything I can do to help with that. 😔

> [CRIT] Exception while executing pipeline Projects/Process: Octokit.AuthorizationException: Bad credentials

**Comment by daveaglick** [comment]
Yeah, don't worry about the build error :). I did a big port of the site a few months ago and still haven't gotten around to putting together a PR CI build script.

**Comment by Turnerj** [comment]
If there is anything I can do to help with that, give me a shout - happy to throw together a cheeky PR or two to help. 🙂

**Comment by daveaglick** [comment]
Finally getting around to merging some of these :)

**Pull request merged**
