### PR TITLE
dsibinski.pl changed to codejourney.net

### PR DESCRIPTION
**Pull request by iks111**
My blog's name and URL have been updated, that's why I'm changing it here ;)

### CODE REVIEW

**Comment by iks111** [comment]
I'd also like to update the image, but don't know what is this "https://pbs.twimg.com" link...

**Comment by daveaglick** [comment]
Awesome, thanks! I’ll take care of the image for you - hoping to get all the outstanding PRs merged tomorrow.

**Comment by iks111** [comment]
Thanks, the new image can be found here: https://www.codejourney.net/wp-content/uploads/2018/10/1300px-na-1300px-JPEG-1.jpg

**Comment by daveaglick** [comment]
Thanks for keeping it updated!

**Pull request merged**
