### PR TITLE
IE11 fixes

### PR DESCRIPTION
**Pull request by JuergenGutsch**
* Fixes the footer issue on #44 and a CSS bug with the logo in the header
* Unfortunately it doesn't fix the JavaScript error on IE11 that causes not to load the data for the two boxes on the left. Will do some more investigation to find a solution.

### CODE REVIEW

**Comment by daveaglick** [comment]
Thanks a ton for taking a look at this! I obviously haven't had a chance to review it closely yet, but hopefully I'll be able to soon.

**Comment by JuergenGutsch** [comment]
No hurry. Maybe I also get that JS error fixed until than.

**Comment by daveaglick** [comment]
Okay - finally carving out some time for Discover .NET in the next couple weeks. I merged this PR locally and noticed some odd sizing when viewing at smaller screen sizes:

2019-04-01_10h43_41

Any thoughts on what's going on here?

**Comment by JuergenGutsch** [comment]
I'll have a look.

**Comment by daveaglick** [comment]
Been working on some redesigns, etc. so I think this is probably overcome by events. Thanks though!

**Pull request closed without merging**
