### PR TITLE
Create Cake.Coverlet

### PR DESCRIPTION
**Pull request by Romanx**

### CODE REVIEW

**Comment by daveaglick** [comment]
Thanks!

**Comment by Romanx** [comment]
Thanks for the tweaks to the pr @daveaglick I'll get it right first time one day!

**Comment by matkoch** [comment]
I don't intent to break anyone's heart, but I don't think that individual addons should be listed. Continuing this approach would render the 'build tools' category pretty much useless.

**Comment by daveaglick** [comment]
@matkoch I definitely think they should be listed somehow. Granted, depending on the host tool or the addon, some may be bigger in scope than others. But if it's got a repository, there's a potential for independent contributions, bug reports, etc. My vision for Discover is to include _everything_.

That said, I also hear what you're saying about polluting the top-level project categories with a bunch of addons. Cake alone has hundreds now. What I'll probably do is add a way to indicate the type of relationship when implementing #214. If the project is an addon of another project, maybe it doesn't get shown on the main projects page but on the page for the host instead.

**Pull request merged**
