### PR TITLE
Update ilovedotnet.yml

### PR DESCRIPTION
**Pull request by fingers10**

### CODE REVIEW

**Comment by daveaglick** [comment]
Thanks for updating with a feed!

**Comment by fingers10** [comment]
> Thanks for updating with a feed!

@daveaglick Why I'm not able to find anything related to ilovedotnet in discoverdot.net? How to find? Please can you assist me?

**Comment by daveaglick** [comment]
Looks like the dates on posts aren't coming over correctly - I'd check how those look on your RSS feed and run it through a validator:

image

**Comment by fingers10** [comment]
> Looks like the dates on posts aren't coming over correctly - I'd check how those look on your RSS feed and run it through a validator:
> 
> image

Right... Lemme know incase of any help. I'll also validate my RSS feed this weekend.

**Pull request merged**
