### PR TITLE
Create chromely

### PR DESCRIPTION
**Pull request by mattkol**
New Chromely blog.

### CODE REVIEW

**Comment by daveaglick** [comment]
Is this a single blog post or a full blog (I.e., will there be additional posts)? If the former, I'd like to hold off and perhaps add some support to the project item directly to handle project-specific blogs and blog posts.

**Comment by mattkol** [comment]
There will be additional posts related to Chromely.
Thanks.

**Comment by daveaglick** [comment]
Okay, thanks. I'm going to hold off merging this until #175 is done, then we'll bring it in and it'll get added to the Chromely project page.

**Comment by daveaglick** [comment]
Closing this out since it's been a couple years and I'm not sure I'll actually get to https://github.com/daveaglick/discoverdotnet/issues/175 any time soon :(.

**Pull request closed without merging**
