### PR TITLE
Add AmbientTasks project

### PR DESCRIPTION
**Pull request by jnm2**

### CODE REVIEW

**Comment by jnm2** [comment]
@daveaglick Oops, did I break something?

**Comment by daveaglick** [comment]
Nope! Definitely me who broke something :)

I’m working as fast as I can to get Statiq to a point where I can circle back here and fix the PR builds (they’re failing because there’s too much data to process at this point for a PR). Then I’ll start merging new data again.

**Comment by jnm2** [comment]
Okay, no hurry for my sake!

**Comment by daveaglick** [comment]
Thanks, and sorry for the delay in getting this merged!

**Comment by jnm2** [comment]
No apology needed! Thanks for what you're doing!

**Pull request merged**
