### PR TITLE
Create builtwithdot.net

### PR DESCRIPTION
**Pull request by Corstiaan84**
:-)

### CODE REVIEW

**Comment by daveaglick** [comment]
You beat me to it! I had sent myself Damien's Tweet so I wouldn't forget. Will merge this in soon - and nice work +1

**Comment by Corstiaan84** [comment]
Good stuff! Shouldn't DiscoverDot.Net be on BuiltWithDot.Net...? ;-)

**Comment by daveaglick** [comment]
Converted this to a resource for now (though I'm still thinking on how best to classify it). My concern with listing it as a blog is that the frequency of content will overwhelm other content-focused blog entries. I may and try to come up with something special to handle this type of situation, but for now it's listed under the Resources section.

**Comment by Corstiaan84** [comment]
Might be better, yes. I could create a feed that only shows the featured projects? That one will be less chatty.

**Pull request merged**
