### PR TITLE
Update CommandQuery

### PR DESCRIPTION
**Pull request by hlaueriksson**
New NuGet: `CommandQuery.GoogleCloudFunctions`
New Tag: `GCP` (Google Cloud Platform)

### CODE REVIEW

**Comment by hlaueriksson** [comment]
Ouch, I see that the build fails with:

```
Error: [D:/a/discoverdotnet/discoverdotnet/data/projects/commandquery.yml => data/projects/commandquery.json] Document contains non-approved tag(s): GCP (ValidateProjectTags)
```

Is `GCP` a tag that should be added?

**Comment by daveaglick** [comment]
There's an Azure tag, so I guess it makes sense to add a GCP one as well (and probably an AWS one). Would you mind adding both of those in https://github.com/daveaglick/discoverdotnet/blob/master/Analyzers/ValidateProjectTags.cs as part of this PR? Thanks!

**Comment by hlaueriksson** [comment]
I added `GCP` in `ValidateProjectTags.cs`.

The build failed at the `actions/setup-dotnet@v1` step, so I thought I might just as well clean up the usings to trigger another build.

**Comment by daveaglick** [comment]
Great work, thanks! Sorry it's taken such a long time to merge this in.

**Pull request merged**
