### PR TITLE
Create anthonygiretti.yml

### PR DESCRIPTION
**Pull request by MaximRouiller**

### CODE REVIEW

**Comment by MaximRouiller** [comment]
@daveaglick feel free to move that `yml` anywhere you want.

Anthony is an MVP and he post often.

**Comment by MaximRouiller** [comment]
I think @daveaglick may not be answering my calls anymore...

**Comment by daveaglick** [comment]
Lol. I'm here, I SWEAR! Just been clearing a _long_ backlog.

**Comment by daveaglick** [comment]
Thanks, and sorry for the delay in getting this merged!

**Pull request merged**
