### PR TITLE
Create konsole

### PR DESCRIPTION
**Pull request by goblinfactory**

### CODE REVIEW

**Comment by goblinfactory** [comment]
Low ceremony, simply to use C# (.NET standard) windowing console library, providing progress bars, windows and forms and drawing for console applications. Build UX's or utilities quickly with few lines of code.

**Comment by daveaglick** [comment]
Thanks! Still doing a little cleanup on Discover after a big engine porting process, but will hopefully be able to merge new data files soon.

**Comment by daveaglick** [comment]
Thanks, and sorry for the extreme delay! I ended up copying this over manually since it needed a little tweaking for the new site layout.

**Comment by goblinfactory** [comment]
oh gosh, this is awesome! like a long lost friend :D

**Pull request closed without merging**
